### ISSUE TITLE
why its showing this app is not valid 

### ISSUE THREAD

**Issue by BharatAgarSoftTech** [danielbierwirth/DropboxBrowser#23]
It's showing when i was trying to login.

![simulator screen shot 15-feb-2017 8 11 18 pm](https://cloud.githubusercontent.com/assets/18732229/22979028/f4c33f26-f3ba-11e6-82c0-a5699981af0b.png)

**Comment by Sam-Spencer** [comment]
Are you using the latest version from the master branch or feature branch?

**Comment by BharatAgarSoftTech** [comment]
Sorry for late reply i was on holiday, i am using latest version from the master.

**Comment by danielbierwirth** [comment]
Hi, did you register your app with Dropbox by creating a new app in Dropbox 'My apps' section? Maybe this one helps: [https://www.dropbox.com/developers/reference/oauth-guide](url)

**Comment by Sam-Spencer** [comment]
I strong urge you to begin transitioning to DropboxBrowser v6, currently available on the feature branch. v6 uses the new Dropbox API and takes advantage of some of its features. Apps that do not use the new Dropbox API will no longer be allowed to authenticate at some point later this year. 

The only reason v6 has not been pushed to master branch is because documentation and testing is not yet complete. That being said, it should be perfectly stable.

**Comment by danielbierwirth** [comment]
Hi Sam, I merged branch 'feature' into master. Thanks for the reminder 👍

**Comment by Sam-Spencer** [comment]
Seeing as this issue should be fixed by changes now available on the master branch, this issue will now be closed. Should there be further discussion or questions related to this issue, it can be reopened. Thank you, @BharatAgarSoftTech.
